modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="balancedhurttimer"
version="${file.jarVersion}"
displayName="Balanced Hurt Timer"
authors="Arekkuusu"
displayURL=""
description="A balanced attack frame remover mod"