license="The MIT License (MIT)"
modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="betterhurttimer"
version="${file.jarVersion}"
certificateFingerprint = "72cd337644e68ff7257f69b2927894048793e577"
displayName="Better Hurt Timer"
authors="Arekkuusu"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer-bht"
logoFile="logo.png"
description="A balanced attack frame remover mod"